sudo: required
dist: trusty
language: python
python:
  - "2.7"
services:
  - docker
env:
  global:
    - PATH="/usr/bin:$PATH"

before_install:
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y -o Dpkg::Options::="--force-confnew" docker-ce

install:
  - sudo pip install docker-py
  - sudo apt-get install -y sshpass software-properties-common python-software-properties
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible
  - sudo rm /usr/bin/python && sudo ln -s /usr/bin/python2.7 /usr/bin/python
  - git clone https://github.com/msgqe/ansible-basic-server
  - cd ansible-basic-server
  - ansible-galaxy install -f -r requirements.yml
  - make test

script:
  # Upstream Artemis works just as fine for this test
  - export AMQ_BROKER_DOWNLOAD_URL=http://www.apache.org/dist/activemq/activemq-artemis/2.5.0/apache-artemis-2.5.0-bin.zip
  - make test
